### ISSUE TITLE
Undefined $default_settings in addCiviCRMHandler()

### ISSUE THREAD

**Issue by herbdool** [fuzionnz/webform_civicrm_migrate#1]
`$default_settings` isn't defined:
https://github.com/fuzionnz/webform_civicrm_migrate/blob/63b45fd3039cfd7dbfe52b27d35f6067a6fe69da/src/EventSubscriber/WebformCivicrmMigrateSubscriber.php#L542

I haven't tested the module yet so we'll see how much of a problem this is.

**Comment by stesi561** [comment]
Hmm. My guess is that this just means the default settings are not being set - but perhaps they are getting set anyway elsewhere which is why I missed this!

Good spotting.

**Comment by stesi561** [comment]
@herbdool I've pushed up a few tweaks. That include fixing the above.
